### ISSUE TITLE
TODO list: documentations

### ISSUE THREAD

**Issue by WuyihanVictor** [aiidaplugins/aiida-dftk#3]
Planed to write 4 jupyter notebooks:
## 1. Setup
   - Julia:
     - [x] DFTK
     - [x] AiidaDFTK
   - Python:
     - [x] aiida-core
     - [x] aiida-DFTK plugin
     - [x] computer
     - [x] code
     - [x] pseudo
---
## 2. First calculation
   - Silicon example from DFTK
     - [x] structure
     - [x] code
     - [x] pseudo
     - [x] kpoints
     - [x] parameters
---
## 3. First base workchain
   - [x] based on previous Si calculation
---
## 4. First common workflow (optional)
  - MoS2 example
    - [x] setup DFTK aiida-common-workflow plugin
    - [x] protocol
